# https://travis-ci.org/jnsebgosselin/pygld

language: python
python: "3.6"

install:
  - pip install xlsxwriter
  - pip install xlrd
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-ordering
  - pip install coveralls
  - pip install codecov
  - pip install matplotlib
  - pip install scipy

script:
  python runtests.py

after_success:
  - coveralls
